export const SET_LOADING = "SET_LOADING";

export const FETCH_ALL_POKEMON_DETAILS = "FETCH_ALL_POKEMON_DETAILS";
export const FETCH_ALL_POKEMON_DETAILS_SUCCESS = "FETCH_ALL_POKEMON_DETAILS_SUCCESS";

export const FETCH_USER_POKEMON_DETAILS = "FETCH_USER_POKEMON_DETAILS";
export const FETCH_USER_POKEMON_DETAILS_SUCCESS = "FETCH_USER_POKEMON_DETAILS_SUCCESS";
export const FETCH_USER_POKEMON_IDS_SUCCESS = "FETCH_USER_POKEMON_IDS_SUCCESS";

export const FETCH_POKEMON_DETAILS_ERROR = "FETCH_MULTIPLE_POKEMON_DETAILS_ERROR";

export const SAVE_POKEMON = "SAVE_POKEMON";
export const SAVE_POKEMON_ERROR = "SAVE_POKEMON_ERROR";

export const REMOVE_POKEMON = "REMOVE_POKEMON";
export const REMOVE_POKEMON_ERROR = "REMOVE_POKEMON_ERROR";


export const SET_TOTAL_POKEMON_COUNT = "FETCH_TOTAL_POKEMON_COUNT";
